### ISSUE TITLE
Ошибка переноса строки

### ISSUE THREAD

**Issue by kirya174** [VladislavEremeev/QA_bible#24]
На странице [по видам тестовой документации](https://vladislaveremeev.gitbook.io/qa_bible/testovaya-dokumentaciya-i-artefakty-test-deliverablestest-artifacts/vidy-testovoi-dokumentacii) ошибка с переносом строки в пункте "Тестовые данные (Test Data)"
![ошибка переноса строки](https://user-images.githubusercontent.com/94140633/172823810-326618d9-2264-474b-8d5e-28e35955c8e1.PNG)
.

**Comment by VladislavEremeev** [comment]
[fixed](https://github.com/VladislavEremeev/QA_bible/commit/ee64092d6be9c8ce3c4323cb940809f06fb428ac)
